#------------------------------------------------------------------------
# Source File Information (DO NOT MODIFY)
# Source ID: 997ac8aa-625e-47a1-8f81-8acb5c7668f6
# Source File: C:\Users\jbaker\Documents\SAPIEN\PowerShell Studio\Projects\Mame_ScreenSaver\Mame_ScreenSaver.psproj
#------------------------------------------------------------------------
#region Project Recovery Data (DO NOT MODIFY)
<#RecoveryData:
tgIAAB+LCAAAAAAABACFUl1vgjAUfTfxP5A+LkHETMQMeVgMiw/7iJi9mloug620pBSn+/W7UDCa
Gfdy21Nuzzn30GANTO5BHZdU03A4sKzgTclPYNqKj4JlSor8B5IFiSivgLSHUc41qAW5G5WV+9DU
wiyJWdxDwdtN2tYKqznJgJcjfdCkFUKpd1BVLkU4GbmB04PuG6rAahnO5zPKfEptbzIF+35GXdtP
fSyU7aZs5nl+6gVO19xd7SbYHEsIx4FzDntyyROUs5xztaoDHbQe65zj5C5OnVF1FsIaUlAgGES1
YBo9L8hK7OUX2AUtYFsxtcUUSNijJhPj8brCmISxpkrXZRPX7c6Tl42qb1p54nJHuTFi9tX/Pq7x
xZn8tp9pLiKpCuRLSdij5h9fEBpggjwFb9Cryj9yQXnT8ILBIAmmEzMFIGKKTxDJSrwQOH86h4PA
uXinvy19T962AgAA#>
#endregion
<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2019 v5.6.156
     Generated on:       12/22/2018 9:04 PM
     Generated by:       jbaker
     Organization:       Innerworkings
    --------------------------------------------------------------------------------
    .DESCRIPTION
        Script generated by PowerShell Studio 2019
#>



#region Source: Startup.pss
#region File Recovery Data (DO NOT MODIFY)
<#RecoveryData:
YQAAAB+LCAAAAAAABACzCUpNzi9LLap0SSxJVAAyijPz82yVjPUMlex4uRQUbPyLMtMz8xJz3DJz
Uv0Sc1PtgksSi0pKC/QKiott9DFkebls9JGNtAMAoyFkEGEAAAA=#>
#endregion
#----------------------------------------------
#region Import Assemblies
#----------------------------------------------
#endregion Import Assemblies

#Define a Param block to use custom parameters in the project
#Param ($CustomParameter)

function Main
{
<#
    .SYNOPSIS
        The Main function starts the project application.
    
    .PARAMETER Commandline
        $Commandline contains the complete argument string passed to the script packager executable.
    
    .NOTES
        Use this function to initialize your script and to call GUI forms.
		
    .NOTES
        To get the console output in the Packager (Forms Engine) use: 
		$ConsoleOutput (Type: System.Collections.ArrayList)
#>
	Param ([String]$Commandline)
	
	#--------------------------------------------------------------------------
	#TODO: Add initialization script here (Load modules and check requirements)	
	#--------------------------------------------------------------------------
		
	if ((Show-MainForm_psf) -eq 'OK')
	{
		
	}
	
	$script:ExitCode = 0 #Set the exit code for the Packager
}
#endregion Source: Startup.pss

#region Source: Globals.ps1
	#--------------------------------------------
	# Declare Global Variables and Functions here
	#--------------------------------------------
	
	function Get-MyDir
	{
	<#
		.SYNOPSIS
			Get-ScriptDirectory returns the proper location of the script.
	
		.OUTPUTS
			System.String
		
		.NOTES
			Returns the correct path within a packaged executable.
	#>
		[OutputType([string])]
		param ()
		if ($null -ne $hostinvocation)
		{
			Split-Path $hostinvocation.MyCommand.path
		}
		else
		{
			Split-Path $script:MyInvocation.MyCommand.Path
		}
	}
	
	function Get-ini
	{
		$config = Get-Content $inifile
		$cfgattributes = @("mamepath", "rompath", "romlistpath", "configpath", "snapshotpath", "nvrampath", "arguments", "runtime", "volume")
		$cfg = @{ }
		
		foreach ($line in $config)
		{
			foreach ($attribute in $cfgattributes)
			{
				$regex = "^\s{0,}($attribute)\s{0,}=\s{0,}(.*)\s{0,}"
				if ($line -match $regex)
				{
					switch ($Matches[1])
					{
						"mamepath" {
							$cfg.mamepath = $Matches[2]
						}
						"rompath" {
							$cfg.rompath = $Matches[2]
						}
						"romlistpath" {
							$cfg.romlistpath = $Matches[2]
						}
						"configpath" {
							$cfg.configpath = $Matches[2]
						}
						"snapshotpath" {
							$cfg.snapshotpath = $Matches[2]
						}
						"nvrampath" {
							$cfg.nvrampath = $Matches[2]
						}
						"arguments" {
							$cfg.arguments = $Matches[2]
						}
						"runtime" {
							$cfg.runtime = $Matches[2]
						}
						"volume" {
							$cfg.volume = $Matches[2]
						}
					}
					break
				}
			}
		}
		
		Return $cfg
	}
	
	[string]$mydir = Get-MyDir
	[string]$mamepath = $null
	[string]$rompath = $null
	[string]$romlistpath = $null
	[string]$configpath = $null
	[string]$snapshotpath = $null
	[string]$nvrampath = $null
	[int]$runtime = 120
	[int]$volume = 0
	
	if (Test-Path "c:\Windows\System32\mame_scr.ini")
	{
		[string]$inifile = "c:\Windows\System32\mame_scr.ini"
	}
	elseif (Test-Path "$mydir\mame_scr.ini")
	{
		[string]$inifile = "$mydir\mame_scr.ini"
	}
	else
	{
		[string]$inifile = "c:\Windows\System32\mame_scr.ini"
	}
#endregion Source: Globals.ps1

#region Source: MainForm.psf
function Show-MainForm_psf
{
#region File Recovery Data (DO NOT MODIFY)
<#RecoveryData:
VRQAAB+LCAAAAAAABAClmEevw0h2hfcPeP+hMVsCwygGoN0Ac04iKYYdcxBzJn/9sMcbA7bhhbWh
oEIVSrx1zvlu/fnO02HP54uL1/iP58tSD/1//AP9J/yPv35//vjjT3Ouy7qPW6FucyPu8r/0uO6F
Ye7+OS7Fn+B/G/73pL/H//r67QvmVjUGMZpmTY6l//PD0Nwa+KuLfQcXnF8f4KScwoxKpqyDOfOm
t1FodD3WvtqheGs776WOfcCvFw0Efn96r6W9SD5Yr5Wp4ZrnL42n6Jb3I2G6VoGKII+24j2/zCWo
9n7bfW4ZbdFywEy7sGiKnHP2QPQz7bf9++NmARH4CWnVw21x9upnuYmfng9eyx14+Sm99Tym2NP1
+FEncnPSG8clyhRPKds848QNRXejowEGpme1JPloDRsPk2n3mUYBI0oB2utrx2Ny0AuyzQ2qKF4c
X+TsvVW5peRoxYfxk3abifevGS9DiMiDSapQ6fcH3sjWDoV+GeatzCdBK31Db825aKg4IFZtnSgr
zPsvc02qRycfh+2yhj+kb9nLBcLxFwFNQdTgMZQnvz/oQhl+sOdqtn4itYmCTiyvgb+gw1n7j4oh
secaauXab0t1td15yXcGZnRwK90yBCqml8aE6wXVQ8zy+yPH21BOBU73PjYINZEjDl2MmVnO7OWh
By/g1ctX3OgrflIsahu2idnbioy7pWwXJzbIMIU4oAVw8Yrfn+KmLiZLnA1sYXytkXkKTN3gV2Yt
jrinP+96KWRxdgIu0xQ8xbcycBgXxVYZUZNEzLW5zfxmGteKfvYmDvBK0zE3fV7dZyV5u8I2a3Zs
W5wFbsIFdu19niMOPrXnxB7e/lwwkm0jAbN1crcnmHH5ucaUHzg1niqIeU3PEsarWs0bcE/bM0ed
MZlwHZt25C4E5eToVBakAidcDsj6+FfH3d6lUGwG906BjiKPOVNPXev3B1NMOumUtuz1a373aoPc
45JjWTi8vPiirzdWb8WWyRU3t01dzFuV25qVDeQ6WQpvvIwBEKk+5OLsFH9/vhhEU1d8BcS91xIn
EY5ZsA1txQAs63TB62y+OBNhN/ma2oJTaIhNiLBTXKFa31hi27u39tlNNrzN//7QQrnpV1JaQ08z
XCQoFeMrgd69+RSOd0h9/lizESCfYZeEj8LWKq0xXbGJLIlmjopS2MA376Cv7bTe7w+kNzRuj7hC
v3EPFLf5HRjtLlLWyePJ4EUuA8VoKSMSM1YytgQ2jRTKEqYIzr2p+FlOomdXTbf70v3fn5V5fUvW
jmeFYqTAD0v0HVZ6xPfhS1meg9TPnCcVqw+JHA4shcg441ba4cabN+tf2nRZKYL5OJSyvPP7E71m
UMrY0oxnH34jJLJbrkQKLLEwIF6dEPH24pmgT7RizAQtwY89Bg5hLHZklWJif707WlD/7U3y/Kj+
raGhmVOQ2WUSoK43DLdgn6xgRi0NIO60u8QLiXPX1DcM+HrlKgvUNw114cVYRQsXNTB/X7Gkalhw
/v5w0I5F6Z3dL7DXAE3wFKH7Pjb2LWauX4/VnYLYZiQJPiMSM5MaMCV8nqdwALNNWjIaL2QuhLX2
tRrao6yme+lQwubmQILVwDoBHGYjybSt/o3SShEOCj2ueR801XiDiZS2WkOkXRjiQUBSlikV80ip
oAnQfP9oIYzVXCepQwD6q6oP4QVF8zJxJFwm+7e+z9si6zLbYRByzvW6fWUHcBe2gtr+gGYLu2Q+
NBzIbiaa/v40G54WcwEg+54tMWEyEEtm5v4RWi93WWB/IRqaFdFxpXtdFRqxL+MN8kHSy/dMpEXh
bfB5WmTeMFjw+2PgOmCej380GdoQDWfCKWgvIyDNl9wSx6qWut9UhYrnB1NfJ7b6sL5VyM4VGpn4
NzZtiq6tAxynbfb7U2ufWQQh0O7MilSeWYCdwzYMBi00WACZayBrAN/FbHyDAFxz4ZaZLtl5pypw
qtE03Q1US9LEIrb9qSnpJjVvhvhrOd9kMdfCODinTqArWrDzRPjqhZgTkXHaTgGrjPY3ZJPH9/oS
qruM5ql/R9iYS23KbOz7+3N/CfYKCu6wZ5WzmLstJoV/Ty/bT7Z2EniVQ70AfjRQ0OhbgoVwHPwY
6qatINxu2xyO0mP4olzSAN3fH3+sKOSzuK3Cel/Fsf8/z8eR/scRTlCQt7RKrrA40kit4Ff0OoxE
XjBE2xCfi9jjJsD+gSU3rcxiYYUiHvbHQxrwKNPhTYUBEpYzxhtEShGHJEOCYDo4k3bGzCIajYVg
9rph1kBVBEf87iyD9aLv/GZaPDReRab5T01JWEd5eSV48QtPB9+rQcZU9MZeeubWfS80sadUTRAQ
GWpjrsq788ewqrdi+/mtHJPWj1gZ9Zzs6mL76NSqqhEFCPrxgq2aJFw+I9GYYp9HXxJE68c5OCEF
US+Id98M51t7lL6V6tPdlSr07YoiguiW/Y6o7yed7SMKyPd2RvJ5Y/SHAXZY1YFDzPEB1yvxWABH
du1k6V5I4BPXrr7a/RKzRWwPY+4w4gmIY8IYgwf5Z7WKYAKlyI+CBWM3sN0m7AiTz1U3K+Su0Mew
dW6oHGQx8bVcfRk2RiiWc8X7zA22j4iUYSvME1UWuMl/Z70r19MpwA5UcGr5CYZaqGA2RLtG1Ts1
Eq8weOP4G+0/3Ff5m/q8h/owOMp7xjSMAsKAdEC7liyq54RMKCVPXDatk2LrZzxB0Wkn4Cgg9i5l
z6udu4/xqRA4s1TLfbl2Kr0BXBNlVddX13A29JVUTOozYQ5Nvz9M/QrGqDOfGhCl0euMUtMFfSO0
E5oNNjHspyGFN2qXcSaXIEcucX7TvWuTWUXbsjENlr6AZwIme6A+Tt6ae0VwME6ig7JkwNpjixRt
WZtTH40ouiJMMKmZ41jO42gyRzzUacmqpeMxBUxdgeu4q5cWfyqQ+fz+gE7DP+TUXslOPWi8BaNJ
57Q7y0zHz8Sw6thb+kr8uxkMyLtAoxoLERY+wlrWOUrZVyFhnL8KQVUsD/fuVD/U+pGjhytOSwcW
1T3hHUH5OkIV09klpYKBURyV9bvIVVgvmR3HxNggXQJP70K2sxdDjOsl84j++zODy6q/GIk0Dfzy
JRs9hbe1KnDk2Inix5W6kov94uwcCxXNb2rImoe5aiAPtTNxCp3w1eD1fQsm0D7EpYjFw0uqMvOd
qmO+XpePxKtgQPd+FogGO79NAQ5FkfXUB5MVcrConKwFAfGsO3Ub1Gs+Kj+2pd9+id8f75NQbbvs
7PgqUzoYNU1ntypr8j0lPZIk4GkDNt9yTmskYMQTM1Dukm9o33cR6vDr+pZ8PtI7dt/Lw0g44Ihp
K8/32gx3CrA6Yn2/TPOVBYQDGWMT1373wtcYpKnk+syAICrNVN8HPER3mop6QfNZ3NE3+dD545bB
h43GUiFX8nMwBAcKQ2GAgqUVVfftkGxapsRJIwExcQc1ZnAu0mshZ3kPyoQbWDRuNY6Q4E725Kem
DlO8etBuP+SeG+sinbsIRx0tAx1KJhoCg14EeG0RlV3FILd4uQLxSftPqMLzQxMfofbcHGqLqlC0
/EnAl5QWWzdfj8AJb+mTZS+6BJmEBiaEFAXfPAVCx3Gb9q4cghdT76SXyroTY3qwri9IkoH1mWEH
O1jkSZkDz2h7or8cvOsOKvDCfg6EwKgWktPh7O0qrQxqUw+d0PIDeH/E7slef2vnOx4W53uqLt+I
sLGyC/37k9LoBvFigVSHCVTutwlxXIzhAZxHbXpe9Dxsnxh9fW6kybfv5d7FSsw7QmXp2wDcLcs+
fhyPz5yprx63/EARA0FwgO+eGWLUpUz0E5RPYMo3YY7dQGofHIDxPfK4z2Xll+fHlItWkaW/JTmd
yUs+4kqAjY/26PTtQrGaLLFt+6VGxJ/dmOq/dz/qbvp9lTQkpnSr1F6nOOH/9fz9+d9GGIiQazDr
GCwKa0ZSVSk/TWOQGhlGMO0cRYAHuw5KuxpxU75TXhzdPCkDTmcAxldWebDmEYi+qxtlxd+ZzFko
IsP8wKNiysB7Ot2np/2ES07QdqH7yrE3axAmhqwpC3+SHfNU4Z3HYQvJQYW1Zi960dkqs+Di3yRL
XnRaNz0O12PzoffRSsNNNOWFsm/QbfGPw3wT7QITuOpfm+Ae3pOnKiTV0mqXHOHHhhvUL27ZBZa8
jOXpKA6l4/EDDrAwutgECR1VFINugArIWOCJh6XojHMkwTedX17Xw0iZHfY1In8rhmHgiltFwQgC
n9eKq2LPWSpbqXfcNHZcuoQdtGaiLZhb0BQGZlBRvnktn7PtpzmsSZp7Ugbsins/uYfkB8cmXlCD
REh4pIe1m9HW9Q+reYESVmr+bMm3IW9kZlyCla8XqKo+qCD5FAdFUtqs9791CoSZP8FNQmiEPwzR
EPZOlYFbzwouxvuWV6hFbVcZdC8OBuvLl//UVRnlx8i2JzQqF2p2cV4KGfyct8KpLLro4xfEWqmq
mHmCWynrWIT6JQ+yC6NJuD19iFZQEZazAsqveTbSEbtPS9cijjOxrL8n/eMYTff0Mqsl7E1uReV1
v3yGk46oTdmvDEBaxrJMZkAqgNCFLAfGQI180B4cIa91lWYIC67EgXbpdJS+J3HZ4yF8rre7HgNk
SI4zBVAYEzinkQq+GsLHmI1zcuwQMJyEXlBt139fOUK4+jJZ7zOb7I8VThJJm/0lw8DfbMkhog28
7eUsX+mphmdaE1FQqDvLTBlht92k2yXTVrdPdZO76xPORYgWQoy+UuW+jnq9H9J82/f7/aTMFvVE
HX9jNG+SBJHrFX90MaG3ydvLLSIAVJ5vKRnR7oJQciAmv7bwZtspj4c3AgA0fGpmYBKbJref7uO4
x8a5Wgi63/IHkfpbUCdhy0K6ad9cZ4/vgrOT9IBzUdjNcSJOH8agi0QWSEMD2YAUDCb1ePdVHX8c
yezVQ8KqiM8jOTmQGpu4lJj12jChc1mi0DNUeEr2wxZd7i1vB8ZWcTyJ5sStCP9Rme30Wr5pdbXn
wEcL3kC/hib5fl/IEJ5WNsvSg2cQ5Au5DPUtK3wIlZOcG4XVcRU4ym1PJey93GZbm1mNj3AQU/Fe
Sy9+ul2GOndOeFpb1PbCi8B0xJHqnTjITdfojhi3RnWawnlV6XRGtrnuMmXDWQyvPAFw6N29sc8M
ljT9J/jva71/X/DRy5J3SVvnyx/g88uf4H+9RvzrX0W+wGZVFAAA#>
#endregion
	#----------------------------------------------
	#region Import the Assemblies
	#----------------------------------------------
	[void][reflection.assembly]::Load('System.Windows.Forms, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089')
	[void][reflection.assembly]::Load('System.Drawing, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
	#endregion Import Assemblies

	#----------------------------------------------
	#region Generated Form Objects
	#----------------------------------------------
	[System.Windows.Forms.Application]::EnableVisualStyles()
	$formMAMEScreensaverConfi = New-Object 'System.Windows.Forms.Form'
	$buttonLoadINI = New-Object 'System.Windows.Forms.Button'
	$buttonLoadDefaults = New-Object 'System.Windows.Forms.Button'
	$buttonSave = New-Object 'System.Windows.Forms.Button'
	$buttonExit = New-Object 'System.Windows.Forms.Button'
	$MyForm = New-Object 'System.Windows.Forms.TabControl'
	$Config = New-Object 'System.Windows.Forms.TabPage'
	$tablelayoutpanel1 = New-Object 'System.Windows.Forms.TableLayoutPanel'
	$textboxnvrampath = New-Object 'System.Windows.Forms.TextBox'
	$textboxsnapshotpath = New-Object 'System.Windows.Forms.TextBox'
	$labelNVRAMPath = New-Object 'System.Windows.Forms.Label'
	$labelSnapshotPath = New-Object 'System.Windows.Forms.Label'
	$textboxINIPATH = New-Object 'System.Windows.Forms.TextBox'
	$numericVolume = New-Object 'System.Windows.Forms.NumericUpDown'
	$Numericruntime = New-Object 'System.Windows.Forms.NumericUpDown'
	$labelVolume = New-Object 'System.Windows.Forms.Label'
	$labelRunTime = New-Object 'System.Windows.Forms.Label'
	$labelIniPath = New-Object 'System.Windows.Forms.Label'
	$textboxromlistpath = New-Object 'System.Windows.Forms.TextBox'
	$labelRomPath = New-Object 'System.Windows.Forms.Label'
	$labelMamePath = New-Object 'System.Windows.Forms.Label'
	$labelRomList = New-Object 'System.Windows.Forms.Label'
	$labelConfigPath = New-Object 'System.Windows.Forms.Label'
	$textboxConfigPath = New-Object 'System.Windows.Forms.TextBox'
	$textboxMamePath = New-Object 'System.Windows.Forms.TextBox'
	$textboxROMPath = New-Object 'System.Windows.Forms.TextBox'
	$labelMameArguments = New-Object 'System.Windows.Forms.Label'
	$textboxMameArguments = New-Object 'System.Windows.Forms.TextBox'
	$tabsetup = New-Object 'System.Windows.Forms.TabPage'
	$tablelayoutpanel3 = New-Object 'System.Windows.Forms.TableLayoutPanel'
	$tabHelp = New-Object 'System.Windows.Forms.TabPage'
	$tablelayoutpanel2 = New-Object 'System.Windows.Forms.TableLayoutPanel'
	$textbox9 = New-Object 'System.Windows.Forms.TextBox'
	$textbox1 = New-Object 'System.Windows.Forms.TextBox'
	$label8 = New-Object 'System.Windows.Forms.Label'
	$label7 = New-Object 'System.Windows.Forms.Label'
	$textbox2 = New-Object 'System.Windows.Forms.TextBox'
	$label3 = New-Object 'System.Windows.Forms.Label'
	$label4 = New-Object 'System.Windows.Forms.Label'
	$labelROMListPath = New-Object 'System.Windows.Forms.Label'
	$label5 = New-Object 'System.Windows.Forms.Label'
	$textbox3 = New-Object 'System.Windows.Forms.TextBox'
	$textbox5 = New-Object 'System.Windows.Forms.TextBox'
	$textbox4 = New-Object 'System.Windows.Forms.TextBox'
	$label6 = New-Object 'System.Windows.Forms.Label'
	$textbox6 = New-Object 'System.Windows.Forms.TextBox'
	$label2 = New-Object 'System.Windows.Forms.Label'
	$label1 = New-Object 'System.Windows.Forms.Label'
	$textbox8 = New-Object 'System.Windows.Forms.TextBox'
	$textbox7 = New-Object 'System.Windows.Forms.TextBox'
	$tabAbout = New-Object 'System.Windows.Forms.TabPage'
	$textbox10 = New-Object 'System.Windows.Forms.TextBox'
	$tooltip1 = New-Object 'System.Windows.Forms.ToolTip'
	$InitialFormWindowState = New-Object 'System.Windows.Forms.FormWindowState'
	#endregion Generated Form Objects

	#----------------------------------------------
	# User Generated Script
	#----------------------------------------------
	
	$formMAMEScreensaverConfi_Load = {
		$cfg = Get-ini
		$textboxINIPATH.Text = $inifile
		$textboxMamePath.Text = $cfg.mamepath
		$textboxROMPath.Text = $cfg.rompath
		$textboxROMListPath.Text = $cfg.romlistpath
		$textboxConfigPath.Text = $cfg.configpath
		$textboxsnapshotpath.Text = $cfg.snapshotpath
		$textboxnvrampath.Text = $cfg.nvrampath
		$Numericruntime.Value = $cfg.runtime
		$numericVolume.Value = $cfg.volume
	}
	
	$buttonSave_Click = {
		[string]$newconfig = "mamepath=$($textboxMamePath.Text)`r`n"
		$newconfig += "rompath=$($textboxROMPath.Text)`r`n"
		$newconfig += "romlistpath=$($textboxromlistpath.Text)`r`n"
		$newconfig += "configpath=$($textboxConfigPath.Text)`r`n"
		$newconfig += "snapshotpath=$($textboxsnapshotpath.Text)`r`n"
		$newconfig += "nvrampath=$($textboxnvrampath.Text)`r`n"
		$newconfig += "runtime=$($Numericruntime.Value)`r`n"
		$newconfig += "volume=$($numericVolume.Value)`r`n"
		$newconfig += "mamearguments=$($textboxMameArguments.Text)`r`n"
		Set-Content -Path $inifile -Value $newconfig
	}
	
	$buttonLoadDefaults_Click = {
		$textboxMamePath.Text = "c:\mame\mame.exe"
		$textboxROMPath.Text = "c:\mame\roms"
		$textboxromlistpath.Text = "c:\mame\romlist.txt"
		$textboxConfigPath.Text = "c:\mame\cfg"
		$textboxsnapshotpath.Text = "c:\mame\snaps"
		$textboxnvrampath.Text = "c:\mame\nvram"
		$textboxMameArguments.Text = $null
		$numericruntime.Value = 120
		$numericVolume.Value = -32
	}
	
	$buttonLoadINI_Click = {
		$cfg = Get-ini	
		$textboxMamePath.Text = $cfg.mamepath
		$textboxROMPath.Text = $cfg.rompath
		$textboxROMListPath.Text = $cfg.romlistpath
		$textboxConfigPath.Text = $cfg.configpath
		$textboxsnapshotpath.Text = $cfg.snapshotpath
		$textboxnvrampath.Text = $cfg.nvrampath
		$Numericruntime.Value = $cfg.runtime
		$numericVolume.Value = $cfg.volume
	}
	
	# --End User Generated Script--
	#----------------------------------------------
	#region Generated Events
	#----------------------------------------------
	
	$Form_StateCorrection_Load=
	{
		#Correct the initial state of the form to prevent the .Net maximized form issue
		$formMAMEScreensaverConfi.WindowState = $InitialFormWindowState
	}
	
	$Form_StoreValues_Closing=
	{
		#Store the control values
		$script:MainForm_textboxnvrampath = $textboxnvrampath.Text
		$script:MainForm_textboxsnapshotpath = $textboxsnapshotpath.Text
		$script:MainForm_textboxINIPATH = $textboxINIPATH.Text
		$script:MainForm_numericVolume = $numericVolume.Value
		$script:MainForm_Numericruntime = $Numericruntime.Value
		$script:MainForm_textboxromlistpath = $textboxromlistpath.Text
		$script:MainForm_textboxConfigPath = $textboxConfigPath.Text
		$script:MainForm_textboxMamePath = $textboxMamePath.Text
		$script:MainForm_textboxROMPath = $textboxROMPath.Text
		$script:MainForm_textboxMameArguments = $textboxMameArguments.Text
		$script:MainForm_textbox9 = $textbox9.Text
		$script:MainForm_textbox1 = $textbox1.Text
		$script:MainForm_textbox2 = $textbox2.Text
		$script:MainForm_textbox3 = $textbox3.Text
		$script:MainForm_textbox5 = $textbox5.Text
		$script:MainForm_textbox4 = $textbox4.Text
		$script:MainForm_textbox6 = $textbox6.Text
		$script:MainForm_textbox8 = $textbox8.Text
		$script:MainForm_textbox7 = $textbox7.Text
		$script:MainForm_textbox10 = $textbox10.Text
	}

	
	$Form_Cleanup_FormClosed=
	{
		#Remove all event handlers from the controls
		try
		{
			$buttonLoadINI.remove_Click($buttonLoadINI_Click)
			$buttonLoadDefaults.remove_Click($buttonLoadDefaults_Click)
			$buttonSave.remove_Click($buttonSave_Click)
			$formMAMEScreensaverConfi.remove_Load($formMAMEScreensaverConfi_Load)
			$formMAMEScreensaverConfi.remove_Load($Form_StateCorrection_Load)
			$formMAMEScreensaverConfi.remove_Closing($Form_StoreValues_Closing)
			$formMAMEScreensaverConfi.remove_FormClosed($Form_Cleanup_FormClosed)
		}
		catch { Out-Null <# Prevent PSScriptAnalyzer warning #> }
	}
	#endregion Generated Events

	#----------------------------------------------
	#region Generated Form Code
	#----------------------------------------------
	$formMAMEScreensaverConfi.SuspendLayout()
	$MyForm.SuspendLayout()
	$Config.SuspendLayout()
	$tablelayoutpanel1.SuspendLayout()
	$numericVolume.BeginInit()
	$Numericruntime.BeginInit()
	$tabsetup.SuspendLayout()
	$tabHelp.SuspendLayout()
	$tablelayoutpanel2.SuspendLayout()
	$tabAbout.SuspendLayout()
	#
	# formMAMEScreensaverConfi
	#
	$formMAMEScreensaverConfi.Controls.Add($buttonLoadINI)
	$formMAMEScreensaverConfi.Controls.Add($buttonLoadDefaults)
	$formMAMEScreensaverConfi.Controls.Add($buttonSave)
	$formMAMEScreensaverConfi.Controls.Add($buttonExit)
	$formMAMEScreensaverConfi.Controls.Add($MyForm)
	$formMAMEScreensaverConfi.AutoScaleDimensions = '16, 32'
	$formMAMEScreensaverConfi.AutoScaleMode = 'Font'
	$formMAMEScreensaverConfi.AutoScroll = $True
	$formMAMEScreensaverConfi.AutoSize = $True
	$formMAMEScreensaverConfi.AutoSizeMode = 'GrowAndShrink'
	$formMAMEScreensaverConfi.ClientSize = '1251, 718'
	$formMAMEScreensaverConfi.Font = 'Verdana, 9.75pt'
	$formMAMEScreensaverConfi.Margin = '15, 13, 15, 13'
	$formMAMEScreensaverConfi.MaximizeBox = $False
	$formMAMEScreensaverConfi.Name = 'formMAMEScreensaverConfi'
	$formMAMEScreensaverConfi.Text = 'MAME Screensaver Configuration'
	$formMAMEScreensaverConfi.add_Load($formMAMEScreensaverConfi_Load)
	#
	# buttonLoadINI
	#
	$buttonLoadINI.Anchor = 'Bottom, Left'
	$buttonLoadINI.Location = '283, 668'
	$buttonLoadINI.Margin = '4, 4, 4, 4'
	$buttonLoadINI.Name = 'buttonLoadINI'
	$buttonLoadINI.Size = '158, 42'
	$buttonLoadINI.TabIndex = 3
	$buttonLoadINI.Text = 'Load .ini'
	$buttonLoadINI.UseCompatibleTextRendering = $True
	$buttonLoadINI.UseVisualStyleBackColor = $True
	$buttonLoadINI.add_Click($buttonLoadINI_Click)
	#
	# buttonLoadDefaults
	#
	$buttonLoadDefaults.Anchor = 'Bottom, Left'
	$buttonLoadDefaults.Font = 'Verdana, 9.75pt'
	$buttonLoadDefaults.Location = '23, 668'
	$buttonLoadDefaults.Margin = '4, 4, 4, 4'
	$buttonLoadDefaults.Name = 'buttonLoadDefaults'
	$buttonLoadDefaults.Size = '231, 42'
	$buttonLoadDefaults.TabIndex = 2
	$buttonLoadDefaults.Text = 'Load Defaults'
	$buttonLoadDefaults.UseCompatibleTextRendering = $True
	$buttonLoadDefaults.UseVisualStyleBackColor = $True
	$buttonLoadDefaults.add_Click($buttonLoadDefaults_Click)
	#
	# buttonSave
	#
	$buttonSave.Anchor = 'Bottom, Right'
	$buttonSave.Location = '968, 670'
	$buttonSave.Margin = '7, 7, 7, 7'
	$buttonSave.Name = 'buttonSave'
	$buttonSave.Size = '123, 39'
	$buttonSave.TabIndex = 1
	$buttonSave.Text = 'Save'
	$buttonSave.UseCompatibleTextRendering = $True
	$buttonSave.UseVisualStyleBackColor = $True
	$buttonSave.add_Click($buttonSave_Click)
	#
	# buttonExit
	#
	$buttonExit.Anchor = 'Bottom, Right'
	$buttonExit.DialogResult = 'OK'
	$buttonExit.Location = '1105, 670'
	$buttonExit.Margin = '7, 7, 7, 7'
	$buttonExit.Name = 'buttonExit'
	$buttonExit.Size = '120, 39'
	$buttonExit.TabIndex = 1
	$buttonExit.Text = 'Exit'
	$buttonExit.UseCompatibleTextRendering = $True
	$buttonExit.UseVisualStyleBackColor = $True
	#
	# MyForm
	#
	$MyForm.Controls.Add($Config)
	$MyForm.Controls.Add($tabsetup)
	$MyForm.Controls.Add($tabHelp)
	$MyForm.Controls.Add($tabAbout)
	$MyForm.Anchor = 'Top, Bottom, Left, Right'
	$MyForm.Location = '15, 2'
	$MyForm.Margin = '7, 7, 7, 7'
	$MyForm.Name = 'MyForm'
	$MyForm.SelectedIndex = 0
	$MyForm.Size = '1233, 662'
	$MyForm.TabIndex = 0
	#
	# Config
	#
	$Config.Controls.Add($tablelayoutpanel1)
	$Config.Location = '8, 46'
	$Config.Margin = '7, 7, 7, 7'
	$Config.Name = 'Config'
	$Config.Padding = '7, 7, 7, 7'
	$Config.Size = '1217, 608'
	$Config.TabIndex = 0
	$Config.Text = 'Config'
	$Config.UseVisualStyleBackColor = $True
	#
	# tablelayoutpanel1
	#
	$tablelayoutpanel1.Controls.Add($textboxnvrampath, 1, 6)
	$tablelayoutpanel1.Controls.Add($textboxsnapshotpath, 1, 5)
	$tablelayoutpanel1.Controls.Add($labelNVRAMPath, 0, 6)
	$tablelayoutpanel1.Controls.Add($labelSnapshotPath, 0, 5)
	$tablelayoutpanel1.Controls.Add($textboxINIPATH, 1, 0)
	$tablelayoutpanel1.Controls.Add($numericVolume, 1, 8)
	$tablelayoutpanel1.Controls.Add($Numericruntime, 1, 7)
	$tablelayoutpanel1.Controls.Add($labelVolume, 0, 8)
	$tablelayoutpanel1.Controls.Add($labelRunTime, 0, 7)
	$tablelayoutpanel1.Controls.Add($labelIniPath, 0, 0)
	$tablelayoutpanel1.Controls.Add($textboxromlistpath, 1, 3)
	$tablelayoutpanel1.Controls.Add($labelRomPath, 0, 2)
	$tablelayoutpanel1.Controls.Add($labelMamePath, 0, 1)
	$tablelayoutpanel1.Controls.Add($labelRomList, 0, 3)
	$tablelayoutpanel1.Controls.Add($labelConfigPath, 0, 4)
	$tablelayoutpanel1.Controls.Add($textboxConfigPath, 1, 4)
	$tablelayoutpanel1.Controls.Add($textboxMamePath, 1, 1)
	$tablelayoutpanel1.Controls.Add($textboxROMPath, 1, 2)
	$tablelayoutpanel1.Controls.Add($labelMameArguments, 0, 9)
	$tablelayoutpanel1.Controls.Add($textboxMameArguments, 1, 9)
	$tablelayoutpanel1.Anchor = 'Top, Bottom, Left, Right'
	$tablelayoutpanel1.AutoSize = $True
	$tablelayoutpanel1.AutoSizeMode = 'GrowAndShrink'
	$tablelayoutpanel1.ColumnCount = 2
	$System_Windows_Forms_ColumnStyle_1 = New-Object 'System.Windows.Forms.ColumnStyle' ('Percent', 24.85549)
	[void]$tablelayoutpanel1.ColumnStyles.Add($System_Windows_Forms_ColumnStyle_1)
	$System_Windows_Forms_ColumnStyle_2 = New-Object 'System.Windows.Forms.ColumnStyle' ('Percent', 75.14451)
	[void]$tablelayoutpanel1.ColumnStyles.Add($System_Windows_Forms_ColumnStyle_2)
	$tablelayoutpanel1.Location = '21, 14'
	$tablelayoutpanel1.Margin = '7, 7, 7, 7'
	$tablelayoutpanel1.Name = 'tablelayoutpanel1'
	$tablelayoutpanel1.RowCount = 10
	$System_Windows_Forms_RowStyle_3 = New-Object 'System.Windows.Forms.RowStyle' ('Percent', 10)
	[void]$tablelayoutpanel1.RowStyles.Add($System_Windows_Forms_RowStyle_3)
	$System_Windows_Forms_RowStyle_4 = New-Object 'System.Windows.Forms.RowStyle' ('Percent', 10)
	[void]$tablelayoutpanel1.RowStyles.Add($System_Windows_Forms_RowStyle_4)
	$System_Windows_Forms_RowStyle_5 = New-Object 'System.Windows.Forms.RowStyle' ('Percent', 10)
	[void]$tablelayoutpanel1.RowStyles.Add($System_Windows_Forms_RowStyle_5)
	$System_Windows_Forms_RowStyle_6 = New-Object 'System.Windows.Forms.RowStyle' ('Percent', 10)
	[void]$tablelayoutpanel1.RowStyles.Add($System_Windows_Forms_RowStyle_6)
	$System_Windows_Forms_RowStyle_7 = New-Object 'System.Windows.Forms.RowStyle' ('Percent', 10)
	[void]$tablelayoutpanel1.RowStyles.Add($System_Windows_Forms_RowStyle_7)
	$System_Windows_Forms_RowStyle_8 = New-Object 'System.Windows.Forms.RowStyle' ('Percent', 10)
	[void]$tablelayoutpanel1.RowStyles.Add($System_Windows_Forms_RowStyle_8)
	$System_Windows_Forms_RowStyle_9 = New-Object 'System.Windows.Forms.RowStyle' ('Percent', 10)
	[void]$tablelayoutpanel1.RowStyles.Add($System_Windows_Forms_RowStyle_9)
	$System_Windows_Forms_RowStyle_10 = New-Object 'System.Windows.Forms.RowStyle' ('Percent', 10)
	[void]$tablelayoutpanel1.RowStyles.Add($System_Windows_Forms_RowStyle_10)
	$System_Windows_Forms_RowStyle_11 = New-Object 'System.Windows.Forms.RowStyle' ('Percent', 10)
	[void]$tablelayoutpanel1.RowStyles.Add($System_Windows_Forms_RowStyle_11)
	$System_Windows_Forms_RowStyle_12 = New-Object 'System.Windows.Forms.RowStyle' ('Percent', 10)
	[void]$tablelayoutpanel1.RowStyles.Add($System_Windows_Forms_RowStyle_12)
	$System_Windows_Forms_RowStyle_13 = New-Object 'System.Windows.Forms.RowStyle' ('Absolute', 20)
	[void]$tablelayoutpanel1.RowStyles.Add($System_Windows_Forms_RowStyle_13)
	$tablelayoutpanel1.Size = '1170, 580'
	$tablelayoutpanel1.TabIndex = 0
	#
	# textboxnvrampath
	#
	$textboxnvrampath.Anchor = 'Left, Right'
	$textboxnvrampath.Location = '294, 357'
	$textboxnvrampath.Margin = '4, 4, 4, 4'
	$textboxnvrampath.Name = 'textboxnvrampath'
	$textboxnvrampath.Size = '872, 39'
	$textboxnvrampath.TabIndex = 5
	#
	# textboxsnapshotpath
	#
	$textboxsnapshotpath.Anchor = 'Left, Right'
	$textboxsnapshotpath.Location = '294, 299'
	$textboxsnapshotpath.Margin = '4, 4, 4, 4'
	$textboxsnapshotpath.Name = 'textboxsnapshotpath'
	$textboxsnapshotpath.Size = '872, 39'
	$textboxsnapshotpath.TabIndex = 5
	#
	# labelNVRAMPath
	#
	$labelNVRAMPath.Anchor = 'Left, Right'
	$labelNVRAMPath.AutoSize = $True
	$labelNVRAMPath.Location = '7, 358'
	$labelNVRAMPath.Margin = '7, 0, 7, 0'
	$labelNVRAMPath.Name = 'labelNVRAMPath'
	$labelNVRAMPath.Size = '276, 38'
	$labelNVRAMPath.TabIndex = 4
	$labelNVRAMPath.Text = 'NVRAM Path:'
	$labelNVRAMPath.UseCompatibleTextRendering = $True
	#
	# labelSnapshotPath
	#
	$labelSnapshotPath.Anchor = 'Left, Right'
	$labelSnapshotPath.AutoSize = $True
	$labelSnapshotPath.Location = '7, 300'
	$labelSnapshotPath.Margin = '7, 0, 7, 0'
	$labelSnapshotPath.Name = 'labelSnapshotPath'
	$labelSnapshotPath.Size = '276, 38'
	$labelSnapshotPath.TabIndex = 4
	$labelSnapshotPath.Text = 'Snapshot Path:'
	$labelSnapshotPath.UseCompatibleTextRendering = $True
	#
	# textboxINIPATH
	#
	$textboxINIPATH.Anchor = 'Left, Right'
	$textboxINIPATH.BackColor = 'ControlLightLight'
	$textboxINIPATH.BorderStyle = 'None'
	$textboxINIPATH.Font = 'Verdana, 7.875pt'
	$textboxINIPATH.Location = '294, 4'
	$textboxINIPATH.Margin = '4, 4, 4, 4'
	$textboxINIPATH.MaxLength = 512
	$textboxINIPATH.Multiline = $True
	$textboxINIPATH.Name = 'textboxINIPATH'
	$textboxINIPATH.ReadOnly = $True
	$textboxINIPATH.Size = '872, 50'
	$textboxINIPATH.TabIndex = 9
	#
	# numericVolume
	#
	$numericVolume.Anchor = 'Left'
	$numericVolume.Location = '297, 473'
	$numericVolume.Margin = '7, 4, 4, 4'
	$numericVolume.Minimum = -32
	$numericVolume.Name = 'numericVolume'
	$numericVolume.Size = '97, 39'
	$numericVolume.TabIndex = 5
	$numericVolume.Value = -32
	#
	# Numericruntime
	#
	$Numericruntime.Anchor = 'Left'
	$Numericruntime.Location = '297, 415'
	$Numericruntime.Margin = '7, 4, 4, 4'
	$Numericruntime.Maximum = 100000
	$Numericruntime.Minimum = 10
	$Numericruntime.Name = 'Numericruntime'
	$Numericruntime.Size = '97, 39'
	$Numericruntime.TabIndex = 1
	$Numericruntime.Value = 120
	#
	# labelVolume
	#
	$labelVolume.Anchor = 'Left, Right'
	$labelVolume.AutoSize = $True
	$labelVolume.Location = '7, 474'
	$labelVolume.Margin = '7, 0, 7, 0'
	$labelVolume.Name = 'labelVolume'
	$labelVolume.Size = '276, 38'
	$labelVolume.TabIndex = 4
	$labelVolume.Text = 'Volume:'
	$labelVolume.UseCompatibleTextRendering = $True
	#
	# labelRunTime
	#
	$labelRunTime.Anchor = 'Left, Right'
	$labelRunTime.AutoSize = $True
	$labelRunTime.Location = '7, 416'
	$labelRunTime.Margin = '7, 0, 7, 0'
	$labelRunTime.Name = 'labelRunTime'
	$labelRunTime.Size = '276, 38'
	$labelRunTime.TabIndex = 3
	$labelRunTime.Text = 'RunTime:'
	$labelRunTime.UseCompatibleTextRendering = $True
	#
	# labelIniPath
	#
	$labelIniPath.Anchor = 'Left, Right'
	$labelIniPath.AutoSize = $True
	$labelIniPath.Location = '7, 10'
	$labelIniPath.Margin = '7, 0, 7, 0'
	$labelIniPath.Name = 'labelIniPath'
	$labelIniPath.Size = '276, 38'
	$labelIniPath.TabIndex = 8
	$labelIniPath.Text = '.ini Path:'
	$labelIniPath.UseCompatibleTextRendering = $True
	#
	# textboxromlistpath
	#
	$textboxromlistpath.Anchor = 'Left, Right'
	$textboxromlistpath.Location = '294, 183'
	$textboxromlistpath.Margin = '4, 4, 4, 4'
	$textboxromlistpath.Name = 'textboxromlistpath'
	$textboxromlistpath.Size = '872, 39'
	$textboxromlistpath.TabIndex = 4
	#
	# labelRomPath
	#
	$labelRomPath.Anchor = 'Left, Right'
	$labelRomPath.AutoSize = $True
	$labelRomPath.Location = '7, 126'
	$labelRomPath.Margin = '7, 0, 7, 0'
	$labelRomPath.Name = 'labelRomPath'
	$labelRomPath.Size = '276, 38'
	$labelRomPath.TabIndex = 1
	$labelRomPath.Text = 'ROM Path:'
	$labelRomPath.UseCompatibleTextRendering = $True
	#
	# labelMamePath
	#
	$labelMamePath.Anchor = 'Left, Right'
	$labelMamePath.AutoSize = $True
	$labelMamePath.Location = '7, 68'
	$labelMamePath.Margin = '7, 0, 7, 0'
	$labelMamePath.Name = 'labelMamePath'
	$labelMamePath.Size = '276, 38'
	$labelMamePath.TabIndex = 0
	$labelMamePath.Text = 'Mame Path:'
	$tooltip1.SetToolTip($labelMamePath, 'include mame file name
ex: c:\mame\mame.exe')
	$labelMamePath.UseCompatibleTextRendering = $True
	#
	# labelRomList
	#
	$labelRomList.Anchor = 'Left, Right'
	$labelRomList.AutoSize = $True
	$labelRomList.Location = '7, 184'
	$labelRomList.Margin = '7, 0, 7, 0'
	$labelRomList.Name = 'labelRomList'
	$labelRomList.Size = '276, 38'
	$labelRomList.TabIndex = 4
	$labelRomList.Text = 'ROM List Path:'
	$labelRomList.UseCompatibleTextRendering = $True
	#
	# labelConfigPath
	#
	$labelConfigPath.Anchor = 'Left, Right'
	$labelConfigPath.AutoSize = $True
	$labelConfigPath.Location = '7, 242'
	$labelConfigPath.Margin = '7, 0, 7, 0'
	$labelConfigPath.Name = 'labelConfigPath'
	$labelConfigPath.Size = '276, 38'
	$labelConfigPath.TabIndex = 2
	$labelConfigPath.Text = 'Config Path:'
	$labelConfigPath.UseCompatibleTextRendering = $True
	#
	# textboxConfigPath
	#
	$textboxConfigPath.Anchor = 'Left, Right'
	$textboxConfigPath.Location = '294, 241'
	$textboxConfigPath.Margin = '4, 4, 4, 4'
	$textboxConfigPath.Name = 'textboxConfigPath'
	$textboxConfigPath.Size = '872, 39'
	$textboxConfigPath.TabIndex = 4
	#
	# textboxMamePath
	#
	$textboxMamePath.Anchor = 'Left, Right'
	$textboxMamePath.Location = '294, 67'
	$textboxMamePath.Margin = '4, 4, 4, 4'
	$textboxMamePath.Name = 'textboxMamePath'
	$textboxMamePath.Size = '872, 39'
	$textboxMamePath.TabIndex = 1
	#
	# textboxROMPath
	#
	$textboxROMPath.Anchor = 'Left, Right'
	$textboxROMPath.Location = '294, 125'
	$textboxROMPath.Margin = '4, 4, 4, 4'
	$textboxROMPath.Name = 'textboxROMPath'
	$textboxROMPath.Size = '872, 39'
	$textboxROMPath.TabIndex = 3
	#
	# labelMameArguments
	#
	$labelMameArguments.Anchor = 'Left, Right'
	$labelMameArguments.AutoSize = $True
	$labelMameArguments.Location = '7, 532'
	$labelMameArguments.Margin = '7, 0, 7, 0'
	$labelMameArguments.Name = 'labelMameArguments'
	$labelMameArguments.Size = '276, 38'
	$labelMameArguments.TabIndex = 6
	$labelMameArguments.Text = 'Mame Arguments:'
	$labelMameArguments.UseCompatibleTextRendering = $True
	#
	# textboxMameArguments
	#
	$textboxMameArguments.Anchor = 'Left, Right'
	$textboxMameArguments.Location = '294, 531'
	$textboxMameArguments.Margin = '4, 4, 4, 4'
	$textboxMameArguments.Name = 'textboxMameArguments'
	$textboxMameArguments.Size = '872, 39'
	$textboxMameArguments.TabIndex = 7
	#
	# tabsetup
	#
	$tabsetup.Controls.Add($tablelayoutpanel3)
	$tabsetup.Location = '8, 46'
	$tabsetup.Margin = '8, 7, 8, 7'
	$tabsetup.Name = 'tabsetup'
	$tabsetup.Padding = '3, 3, 3, 3'
	$tabsetup.Size = '1217, 608'
	$tabsetup.TabIndex = 3
	$tabsetup.Text = 'Setup'
	$tabsetup.UseVisualStyleBackColor = $True
	#
	# tablelayoutpanel3
	#
	$tablelayoutpanel3.ColumnCount = 2
	$System_Windows_Forms_ColumnStyle_14 = New-Object 'System.Windows.Forms.ColumnStyle' ('Percent', 15.6485357)
	[void]$tablelayoutpanel3.ColumnStyles.Add($System_Windows_Forms_ColumnStyle_14)
	$System_Windows_Forms_ColumnStyle_15 = New-Object 'System.Windows.Forms.ColumnStyle' ('Percent', 84.35146)
	[void]$tablelayoutpanel3.ColumnStyles.Add($System_Windows_Forms_ColumnStyle_15)
	$tablelayoutpanel3.Location = '11, 10'
	$tablelayoutpanel3.Margin = '8, 7, 8, 7'
	$tablelayoutpanel3.Name = 'tablelayoutpanel3'
	$tablelayoutpanel3.RowCount = 2
	$System_Windows_Forms_RowStyle_16 = New-Object 'System.Windows.Forms.RowStyle' ('Percent', 10.8843536)
	[void]$tablelayoutpanel3.RowStyles.Add($System_Windows_Forms_RowStyle_16)
	$System_Windows_Forms_RowStyle_17 = New-Object 'System.Windows.Forms.RowStyle' ('Percent', 89.11565)
	[void]$tablelayoutpanel3.RowStyles.Add($System_Windows_Forms_RowStyle_17)
	$tablelayoutpanel3.Size = '1195, 588'
	$tablelayoutpanel3.TabIndex = 0
	#
	# tabHelp
	#
	$tabHelp.Controls.Add($tablelayoutpanel2)
	$tabHelp.Location = '8, 46'
	$tabHelp.Margin = '7, 7, 7, 7'
	$tabHelp.Name = 'tabHelp'
	$tabHelp.Padding = '7, 7, 7, 7'
	$tabHelp.Size = '1217, 608'
	$tabHelp.TabIndex = 1
	$tabHelp.Text = 'Help'
	$tabHelp.UseVisualStyleBackColor = $True
	#
	# tablelayoutpanel2
	#
	$tablelayoutpanel2.Controls.Add($textbox9, 1, 4)
	$tablelayoutpanel2.Controls.Add($textbox1, 1, 5)
	$tablelayoutpanel2.Controls.Add($label8, 0, 4)
	$tablelayoutpanel2.Controls.Add($label7, 0, 5)
	$tablelayoutpanel2.Controls.Add($textbox2, 1, 2)
	$tablelayoutpanel2.Controls.Add($label3, 0, 1)
	$tablelayoutpanel2.Controls.Add($label4, 0, 0)
	$tablelayoutpanel2.Controls.Add($labelROMListPath, 0, 2)
	$tablelayoutpanel2.Controls.Add($label5, 0, 3)
	$tablelayoutpanel2.Controls.Add($textbox3, 1, 3)
	$tablelayoutpanel2.Controls.Add($textbox5, 1, 1)
	$tablelayoutpanel2.Controls.Add($textbox4, 1, 0)
	$tablelayoutpanel2.Controls.Add($label6, 0, 8)
	$tablelayoutpanel2.Controls.Add($textbox6, 1, 8)
	$tablelayoutpanel2.Controls.Add($label2, 0, 7)
	$tablelayoutpanel2.Controls.Add($label1, 0, 6)
	$tablelayoutpanel2.Controls.Add($textbox8, 1, 7)
	$tablelayoutpanel2.Controls.Add($textbox7, 1, 6)
	$tablelayoutpanel2.Anchor = 'Top, Bottom, Left, Right'
	$tablelayoutpanel2.AutoSize = $True
	$tablelayoutpanel2.AutoSizeMode = 'GrowAndShrink'
	$tablelayoutpanel2.ColumnCount = 2
	$System_Windows_Forms_ColumnStyle_18 = New-Object 'System.Windows.Forms.ColumnStyle' ('Percent', 23.45506)
	[void]$tablelayoutpanel2.ColumnStyles.Add($System_Windows_Forms_ColumnStyle_18)
	$System_Windows_Forms_ColumnStyle_19 = New-Object 'System.Windows.Forms.ColumnStyle' ('Percent', 76.5449448)
	[void]$tablelayoutpanel2.ColumnStyles.Add($System_Windows_Forms_ColumnStyle_19)
	$tablelayoutpanel2.Location = '14, 11'
	$tablelayoutpanel2.Margin = '7, 7, 7, 7'
	$tablelayoutpanel2.Name = 'tablelayoutpanel2'
	$tablelayoutpanel2.RowCount = 9
	$System_Windows_Forms_RowStyle_20 = New-Object 'System.Windows.Forms.RowStyle' ('Percent', 11.1111088)
	[void]$tablelayoutpanel2.RowStyles.Add($System_Windows_Forms_RowStyle_20)
	$System_Windows_Forms_RowStyle_21 = New-Object 'System.Windows.Forms.RowStyle' ('Percent', 11.1111116)
	[void]$tablelayoutpanel2.RowStyles.Add($System_Windows_Forms_RowStyle_21)
	$System_Windows_Forms_RowStyle_22 = New-Object 'System.Windows.Forms.RowStyle' ('Percent', 11.1111116)
	[void]$tablelayoutpanel2.RowStyles.Add($System_Windows_Forms_RowStyle_22)
	$System_Windows_Forms_RowStyle_23 = New-Object 'System.Windows.Forms.RowStyle' ('Percent', 11.1111116)
	[void]$tablelayoutpanel2.RowStyles.Add($System_Windows_Forms_RowStyle_23)
	$System_Windows_Forms_RowStyle_24 = New-Object 'System.Windows.Forms.RowStyle' ('Percent', 11.1111116)
	[void]$tablelayoutpanel2.RowStyles.Add($System_Windows_Forms_RowStyle_24)
	$System_Windows_Forms_RowStyle_25 = New-Object 'System.Windows.Forms.RowStyle' ('Percent', 11.1111116)
	[void]$tablelayoutpanel2.RowStyles.Add($System_Windows_Forms_RowStyle_25)
	$System_Windows_Forms_RowStyle_26 = New-Object 'System.Windows.Forms.RowStyle' ('Percent', 11.1111116)
	[void]$tablelayoutpanel2.RowStyles.Add($System_Windows_Forms_RowStyle_26)
	$System_Windows_Forms_RowStyle_27 = New-Object 'System.Windows.Forms.RowStyle' ('Percent', 11.1111116)
	[void]$tablelayoutpanel2.RowStyles.Add($System_Windows_Forms_RowStyle_27)
	$System_Windows_Forms_RowStyle_28 = New-Object 'System.Windows.Forms.RowStyle' ('Percent', 11.1111116)
	[void]$tablelayoutpanel2.RowStyles.Add($System_Windows_Forms_RowStyle_28)
	$tablelayoutpanel2.Size = '1175, 539'
	$tablelayoutpanel2.TabIndex = 1
	#
	# textbox9
	#
	$textbox9.Anchor = 'Left, Right'
	$textbox9.BackColor = 'ControlLightLight'
	$textbox9.BorderStyle = 'None'
	$textbox9.Location = '279, 245'
	$textbox9.Margin = '4, 4, 4, 4'
	$textbox9.Multiline = $True
	$textbox9.Name = 'textbox9'
	$textbox9.ReadOnly = $True
	$textbox9.Size = '892, 40'
	$textbox9.TabIndex = 5
	$textbox9.Text = 'Location of the MAME snapshots.'
	#
	# textbox1
	#
	$textbox1.Anchor = 'Left, Right'
	$textbox1.BackColor = 'ControlLightLight'
	$textbox1.BorderStyle = 'None'
	$textbox1.Location = '279, 304'
	$textbox1.Margin = '4, 4, 4, 4'
	$textbox1.Multiline = $True
	$textbox1.Name = 'textbox1'
	$textbox1.ReadOnly = $True
	$textbox1.Size = '892, 40'
	$textbox1.TabIndex = 5
	$textbox1.Text = 'Location of the MAME NVRAM files.'
	#
	# label8
	#
	$label8.Anchor = 'Left, Right'
	$label8.AutoSize = $True
	$label8.Location = '7, 246'
	$label8.Margin = '7, 0, 7, 0'
	$label8.Name = 'label8'
	$label8.Size = '261, 38'
	$label8.TabIndex = 4
	$label8.Text = 'Snapshot Path:'
	$label8.TextAlign = 'MiddleLeft'
	$label8.UseCompatibleTextRendering = $True
	#
	# label7
	#
	$label7.Anchor = 'Left, Right'
	$label7.AutoSize = $True
	$label7.Location = '7, 305'
	$label7.Margin = '7, 0, 7, 0'
	$label7.Name = 'label7'
	$label7.Size = '261, 38'
	$label7.TabIndex = 4
	$label7.Text = 'NVRAM Path:'
	$label7.TextAlign = 'MiddleLeft'
	$label7.UseCompatibleTextRendering = $True
	#
	# textbox2
	#
	$textbox2.Anchor = 'Left, Right'
	$textbox2.BackColor = 'ControlLightLight'
	$textbox2.BorderStyle = 'None'
	$textbox2.Location = '279, 131'
	$textbox2.Margin = '4, 4, 4, 4'
	$textbox2.Multiline = $True
	$textbox2.Name = 'textbox2'
	$textbox2.ReadOnly = $True
	$textbox2.Size = '892, 33'
	$textbox2.TabIndex = 4
	$textbox2.Text = 'Path to list containing rom names to be used for screensaver.
Example: c:\mame\myromlist.txt'
	#
	# label3
	#
	$label3.Anchor = 'Left, Right'
	$label3.AutoSize = $True
	$label3.Location = '7, 69'
	$label3.Margin = '7, 0, 7, 0'
	$label3.Name = 'label3'
	$label3.Size = '261, 38'
	$label3.TabIndex = 1
	$label3.Text = 'ROM Path:'
	$label3.TextAlign = 'MiddleLeft'
	$label3.UseCompatibleTextRendering = $True
	#
	# label4
	#
	$label4.Anchor = 'Left, Right'
	$label4.AutoSize = $True
	$label4.Location = '7, 10'
	$label4.Margin = '7, 0, 7, 0'
	$label4.Name = 'label4'
	$label4.Size = '261, 38'
	$label4.TabIndex = 0
	$label4.Text = 'Mame Path:'
	$label4.TextAlign = 'MiddleLeft'
	$label4.UseCompatibleTextRendering = $True
	#
	# labelROMListPath
	#
	$labelROMListPath.Anchor = 'Left, Right'
	$labelROMListPath.AutoSize = $True
	$labelROMListPath.Location = '7, 128'
	$labelROMListPath.Margin = '7, 0, 7, 0'
	$labelROMListPath.Name = 'labelROMListPath'
	$labelROMListPath.Size = '261, 38'
	$labelROMListPath.TabIndex = 4
	$labelROMListPath.Text = 'ROM List Path:'
	$labelROMListPath.TextAlign = 'MiddleLeft'
	$labelROMListPath.UseCompatibleTextRendering = $True
	#
	# label5
	#
	$label5.Anchor = 'Left, Right'
	$label5.AutoSize = $True
	$label5.Location = '7, 187'
	$label5.Margin = '7, 0, 7, 0'
	$label5.Name = 'label5'
	$label5.Size = '261, 38'
	$label5.TabIndex = 2
	$label5.Text = 'Config Path:'
	$label5.TextAlign = 'MiddleLeft'
	$label5.UseCompatibleTextRendering = $True
	#
	# textbox3
	#
	$textbox3.Anchor = 'Left, Right'
	$textbox3.BackColor = 'ControlLightLight'
	$textbox3.BorderStyle = 'None'
	$textbox3.Location = '279, 186'
	$textbox3.Margin = '4, 4, 4, 4'
	$textbox3.Multiline = $True
	$textbox3.Name = 'textbox3'
	$textbox3.ReadOnly = $True
	$textbox3.Size = '892, 40'
	$textbox3.TabIndex = 4
	$textbox3.Text = 'Location of the MAME config files.'
	#
	# textbox5
	#
	$textbox5.Anchor = 'Left, Right'
	$textbox5.BackColor = 'ControlLightLight'
	$textbox5.BorderStyle = 'None'
	$textbox5.Location = '279, 69'
	$textbox5.Margin = '4, 4, 4, 4'
	$textbox5.Multiline = $True
	$textbox5.Name = 'textbox5'
	$textbox5.ReadOnly = $True
	$textbox5.Size = '892, 39'
	$textbox5.TabIndex = 3
	$textbox5.Text = 'Path to location of mame rom files.  Example: c:\mame\roms'
	#
	# textbox4
	#
	$textbox4.Anchor = 'Left, Right'
	$textbox4.BackColor = 'ControlLightLight'
	$textbox4.BorderStyle = 'None'
	$textbox4.Location = '279, 13'
	$textbox4.Margin = '4, 4, 4, 4'
	$textbox4.Multiline = $True
	$textbox4.Name = 'textbox4'
	$textbox4.ReadOnly = $True
	$textbox4.Size = '892, 32'
	$textbox4.TabIndex = 1
	$textbox4.Text = 'Location of mame executable including mame file name.
Example. c:\mame\mame.exe'
	#
	# label6
	#
	$label6.Anchor = 'Left, Right'
	$label6.AutoSize = $True
	$label6.Location = '7, 486'
	$label6.Margin = '7, 0, 7, 0'
	$label6.Name = 'label6'
	$label6.Size = '261, 38'
	$label6.TabIndex = 6
	$label6.Text = 'Mame Arguments:'
	$label6.TextAlign = 'MiddleLeft'
	$label6.UseCompatibleTextRendering = $True
	#
	# textbox6
	#
	$textbox6.Anchor = 'Left, Right'
	$textbox6.BackColor = 'ControlLightLight'
	$textbox6.BorderStyle = 'None'
	$textbox6.Location = '279, 487'
	$textbox6.Margin = '4, 4, 4, 4'
	$textbox6.Multiline = $True
	$textbox6.Name = 'textbox6'
	$textbox6.ReadOnly = $True
	$textbox6.Size = '892, 37'
	$textbox6.TabIndex = 7
	$textbox6.Text = 'Any extra arguments you want to pass to mame executable.'
	#
	# label2
	#
	$label2.Anchor = 'Left, Right'
	$label2.AutoSize = $True
	$label2.Location = '7, 423'
	$label2.Margin = '7, 0, 7, 0'
	$label2.Name = 'label2'
	$label2.Size = '261, 38'
	$label2.TabIndex = 4
	$label2.Text = 'Volume:'
	$label2.UseCompatibleTextRendering = $True
	#
	# label1
	#
	$label1.Anchor = 'Left, Right'
	$label1.AutoSize = $True
	$label1.Location = '7, 364'
	$label1.Margin = '7, 0, 7, 0'
	$label1.Name = 'label1'
	$label1.Size = '261, 38'
	$label1.TabIndex = 3
	$label1.Text = 'RunTime:'
	$label1.UseCompatibleTextRendering = $True
	#
	# textbox8
	#
	$textbox8.Anchor = 'Left, Right'
	$textbox8.BackColor = 'ControlLightLight'
	$textbox8.BorderStyle = 'None'
	$textbox8.Location = '279, 424'
	$textbox8.Margin = '4, 4, 4, 4'
	$textbox8.Multiline = $True
	$textbox8.Name = 'textbox8'
	$textbox8.ReadOnly = $True
	$textbox8.Size = '892, 37'
	$textbox8.TabIndex = 9
	$textbox8.Text = 'Volume of running ROM'
	#
	# textbox7
	#
	$textbox7.Anchor = 'Left, Right'
	$textbox7.BackColor = 'ControlLightLight'
	$textbox7.BorderStyle = 'None'
	$textbox7.Location = '279, 365'
	$textbox7.Margin = '4, 4, 4, 4'
	$textbox7.Multiline = $True
	$textbox7.Name = 'textbox7'
	$textbox7.ReadOnly = $True
	$textbox7.Size = '892, 37'
	$textbox7.TabIndex = 8
	$textbox7.Text = 'Amount of time in seconds to run ROM.'
	#
	# tabAbout
	#
	$tabAbout.Controls.Add($textbox10)
	$tabAbout.Location = '8, 46'
	$tabAbout.Margin = '8, 7, 8, 7'
	$tabAbout.Name = 'tabAbout'
	$tabAbout.Padding = '3, 3, 3, 3'
	$tabAbout.Size = '1217, 608'
	$tabAbout.TabIndex = 2
	$tabAbout.Text = 'About'
	$tabAbout.UseVisualStyleBackColor = $True
	#
	# textbox10
	#
	$textbox10.Anchor = 'Top, Bottom, Left, Right'
	$textbox10.BackColor = 'Window'
	$textbox10.BorderStyle = 'None'
	$textbox10.Location = '8, 10'
	$textbox10.Margin = '8, 7, 8, 7'
	$textbox10.Multiline = $True
	$textbox10.Name = 'textbox10'
	$textbox10.ReadOnly = $True
	$textbox10.Size = '1194, 598'
	$textbox10.TabIndex = 0
	$textbox10.Text = 'Version: 0.1-Alpha'
	#
	# tooltip1
	#
	$tabAbout.ResumeLayout()
	$tablelayoutpanel2.ResumeLayout()
	$tabHelp.ResumeLayout()
	$tabsetup.ResumeLayout()
	$Numericruntime.EndInit()
	$numericVolume.EndInit()
	$tablelayoutpanel1.ResumeLayout()
	$Config.ResumeLayout()
	$MyForm.ResumeLayout()
	$formMAMEScreensaverConfi.ResumeLayout()
	#endregion Generated Form Code

	#----------------------------------------------

	#Save the initial state of the form
	$InitialFormWindowState = $formMAMEScreensaverConfi.WindowState
	#Init the OnLoad event to correct the initial state of the form
	$formMAMEScreensaverConfi.add_Load($Form_StateCorrection_Load)
	#Clean up the control events
	$formMAMEScreensaverConfi.add_FormClosed($Form_Cleanup_FormClosed)
	#Store the control values when form is closing
	$formMAMEScreensaverConfi.add_Closing($Form_StoreValues_Closing)
	#Show the Form
	return $formMAMEScreensaverConfi.ShowDialog()

}
#endregion Source: MainForm.psf

#Start the application
Main ($CommandLine)
